package com.arnyminerz.wallet.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFAA3711)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onPrimaryContainer = Color(0xFF3A0A00)
val md_theme_light_secondary = Color(0xFF336B00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFA1F962)
val md_theme_light_onSecondaryContainer = Color(0xFF0B2000)
val md_theme_light_tertiary = Color(0xFF006686)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC0E8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F2B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A18)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A18)
val md_theme_light_surfaceVariant = Color(0xFFF5DED7)
val md_theme_light_onSurfaceVariant = Color(0xFF53433F)
val md_theme_light_outline = Color(0xFF85736E)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEB)
val md_theme_light_inverseSurface = Color(0xFF362F2D)
val md_theme_light_inversePrimary = Color(0xFFFFB59F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFAA3711)
val md_theme_light_outlineVariant = Color(0xFFD8C2BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB59F)
val md_theme_dark_onPrimary = Color(0xFF5F1600)
val md_theme_dark_primaryContainer = Color(0xFF862300)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_secondary = Color(0xFF87DC48)
val md_theme_dark_onSecondary = Color(0xFF173800)
val md_theme_dark_secondaryContainer = Color(0xFF255100)
val md_theme_dark_onSecondaryContainer = Color(0xFFA1F962)
val md_theme_dark_tertiary = Color(0xFF6FD2FF)
val md_theme_dark_onTertiary = Color(0xFF003547)
val md_theme_dark_tertiaryContainer = Color(0xFF004D66)
val md_theme_dark_onTertiaryContainer = Color(0xFFC0E8FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DC)
val md_theme_dark_surface = Color(0xFF201A18)
val md_theme_dark_onSurface = Color(0xFFEDE0DC)
val md_theme_dark_surfaceVariant = Color(0xFF53433F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BC)
val md_theme_dark_outline = Color(0xFFA08C87)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DC)
val md_theme_dark_inversePrimary = Color(0xFFAA3711)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB59F)
val md_theme_dark_outlineVariant = Color(0xFF53433F)
val md_theme_dark_scrim = Color(0xFF000000)


val colorGreen = Color(0xff66bb6a)
val colorRed = Color(0xffef5350)


val seed = Color(0xFFCD5029)
